# Generated by Django 4.1.7 on 2023-04-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academize', '0002_remove_marks_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='sub',
        ),
        migrations.AddField(
            model_name='semester',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='subject',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='academize.subject'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
