# Generated by Django 4.1.7 on 2023-04-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academize', '0004_remove_semester_marks_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='studName',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='academize.student'),
            preserve_default=False,
        ),
    ]
