# Generated by Django 4.1.7 on 2023-04-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academize', '0005_marks_studname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='studName',
            new_name='student_name',
        ),
    ]
