# Generated by Django 4.1.7 on 2023-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academize', '0006_rename_studname_marks_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sub',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester_num',
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_num',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
