# Generated by Django 4.1.7 on 2023-04-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academize', '0009_rename_student_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='student_name',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='academize.students'),
            preserve_default=False,
        ),
    ]
