# Generated by Django 4.1.7 on 2023-04-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academize', '0011_students_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='semester_num',
            field=models.IntegerField(default=0),
        ),
    ]
