# Generated by Django 4.1.7 on 2023-04-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academize', '0015_mark_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
