# Generated by Django 4.1.7 on 2023-06-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academize', '0017_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='username',
        ),
    ]
